"""Offline maintenance only. Natural Earth v5.1.2 map units + countries; pycountry 26.2.16.
Usage: python scripts/generate-globe-catalog.py MAP_UNITS.geojson COUNTRIES.geojson LAND.geojson LAKES.geojson
The committed catalog is the runtime source. No border/geolocation service is used.
"""
import json, sys, random, re
from pathlib import Path

# City-only maintenance mode leaves the existing region catalog/migration intact.
# Usage: python scripts/generate-globe-catalog.py --cities POPULATED_PLACES.geojson SEED.sql
if sys.argv[1] == '--cities':
    valid_regions = set(re.findall(r'"key":"([A-Z]{2})"', Path('shared/globe-regions.js').read_text()))
    cities = []
    for feature in json.load(open(sys.argv[2]))['features']:
        p = feature['properties']
        if p.get('ISO_A2') not in valid_regions: continue
        cities.append({'key': 'ne-' + str(p['NE_ID']), 'regionKey': p['ISO_A2'],
            'name': p.get('NAME_EN') or p['NAME'], 'adminName': p.get('ADM1NAME') or '',
            'latitude': round(p['LATITUDE'], 6), 'longitude': round(p['LONGITUDE'], 6)})
    cities.extend(json.loads(Path('assets/globe/city-supplements.json').read_text()))
    cities.sort(key=lambda c: (c['regionKey'], c['name'], c['adminName'], c['key']))
    assert len({c['key'] for c in cities}) == len(cities)
    assert all(c['regionKey'] in valid_regions and -90 <= c['latitude'] <= 90 and -180 <= c['longitude'] <= 180 for c in cities)
    Path('shared/globe-cities.js').write_text('// Generated by scripts/generate-globe-catalog.py. Sources: assets/globe/SOURCES.md. Public city anchors only.\n'
        + 'export const GLOBE_CITIES = ' + json.dumps(cities, ensure_ascii=False, separators=(',', ':'))
        + ';\nexport const GLOBE_CITY_BY_KEY = new Map(GLOBE_CITIES.map(city => [city.key, city]));\n'
        + 'export const GLOBE_CITIES_BY_REGION = new Map();\n'
        + 'for (const city of GLOBE_CITIES) {\n  if (!GLOBE_CITIES_BY_REGION.has(city.regionKey)) GLOBE_CITIES_BY_REGION.set(city.regionKey, []);\n'
        + '  GLOBE_CITIES_BY_REGION.get(city.regionKey).push(city);\n}\n')
    quote = lambda s: "'" + s.replace("'", "''") + "'"
    Path(sys.argv[3]).write_text('insert into public.globe_cities (city_key, region_key) values\n'
        + ',\n'.join('(' + quote(c['key']) + ',' + quote(c['regionKey']) + ')' for c in cities) + ';\n')
    print(f'{len(cities)} city anchors; {Path("shared/globe-cities.js").stat().st_size} bytes; no member coordinates')
    sys.exit(0)

import pycountry
from shapely.geometry import shape, Point
from shapely.ops import unary_union

map_units = json.load(open(sys.argv[1]))['features']
countries = json.load(open(sys.argv[2]))['features']
physical_land = unary_union([shape(f['geometry']) for f in json.load(open(sys.argv[3]))['features']]).buffer(0)
lakes = unary_union([shape(f['geometry']) for f in json.load(open(sys.argv[4]))['features']]).buffer(0)
regions = []
for country in sorted(pycountry.countries, key=lambda c: c.name):
    code = country.alpha_2
    # Map units split overseas territories correctly; countries fills UM.
    matches = [f for f in map_units if f['properties'].get('ISO_A2_EH') == code]
    if not matches: matches = [f for f in countries if f['properties'].get('ISO_A2_EH') == code]
    if not matches:
        raise ValueError(f'Missing ISO territory: {code}')
    land = unary_union([shape(f['geometry']) for f in matches]).buffer(0).intersection(physical_land).difference(lakes).buffer(0)
    if land.is_empty: raise ValueError(f'Physical land missing: {code}')
    polygons = list(land.geoms) if land.geom_type == 'MultiPolygon' else [land]
    polygons.sort(key=lambda p: p.area, reverse=True)
    # Limit to 16 representative land positions, with no runtime geographic jitter.
    points = [polygons[0].representative_point()]
    rng = random.Random(code)
    minx, miny, maxx, maxy = land.bounds
    for _ in range(40000):
        if len(points) == 16: break
        p = Point(rng.uniform(minx,maxx), rng.uniform(miny,maxy))
        if land.contains(p) and all(p.distance(q) > min(0.2, (land.area ** .5) / 15) for q in points):
            points.append(p)
    # Small islands use representative points if rejection sampling is sparse.
    for polygon in polygons:
        if len(points) == 16: break
        p = polygon.representative_point()
        if all(p.distance(q) > 1e-7 for q in points): points.append(p)
    anchors = []
    for p in points:
        rounded = Point(round(p.x,6),round(p.y,6))
        if not land.covers(rounded): raise ValueError(f'Anchor outside land: {code}')
        anchors.append([rounded.y,rounded.x])
    regions.append({'key':code,'name':country.name,'anchors':anchors})
assert len(regions) == 249
Path('shared/globe-regions.js').write_text('// Generated by scripts/generate-globe-catalog.py. Natural Earth v5.1.2 (public domain).\n'
    + 'export const GLOBE_REGIONS = ' + json.dumps(regions,ensure_ascii=False,separators=(',',':'))
    + ';\nexport const GLOBE_REGION_BY_KEY = new Map(GLOBE_REGIONS.map(region => [region.key, region]));\n'
    + 'export const GLOBE_CONSENT_VERSION = "2026-09-30";\n'
    + 'export const GLOBE_CITY_CONSENT_VERSION = "2026-10-01";\n')
print(f'{len(regions)} regions; {sum(len(r["anchors"]) for r in regions)} verified land anchors')
