-- Optional account-level membership. No private-profile/locale backfill.
begin;
create table public.globe_regions (
  region_key text primary key,
  name text not null
);
alter table public.globe_regions enable row level security;
revoke all on public.globe_regions from public, anon, authenticated, service_role;
grant select on public.globe_regions to authenticated, service_role;
create policy globe_regions_read on public.globe_regions for select to authenticated using (true);
insert into public.globe_regions (region_key,name) values
('AF','Afghanistan'),
('AL','Albania'),
('DZ','Algeria'),
('AS','American Samoa'),
('AD','Andorra'),
('AO','Angola'),
('AI','Anguilla'),
('AQ','Antarctica'),
('AG','Antigua and Barbuda'),
('AR','Argentina'),
('AM','Armenia'),
('AW','Aruba'),
('AU','Australia'),
('AT','Austria'),
('AZ','Azerbaijan'),
('BS','Bahamas'),
('BH','Bahrain'),
('BD','Bangladesh'),
('BB','Barbados'),
('BY','Belarus'),
('BE','Belgium'),
('BZ','Belize'),
('BJ','Benin'),
('BM','Bermuda'),
('BT','Bhutan'),
('BO','Bolivia, Plurinational State of'),
('BQ','Bonaire, Sint Eustatius and Saba'),
('BA','Bosnia and Herzegovina'),
('BW','Botswana'),
('BV','Bouvet Island'),
('BR','Brazil'),
('IO','British Indian Ocean Territory'),
('BN','Brunei Darussalam'),
('BG','Bulgaria'),
('BF','Burkina Faso'),
('BI','Burundi'),
('CV','Cabo Verde'),
('KH','Cambodia'),
('CM','Cameroon'),
('CA','Canada'),
('KY','Cayman Islands'),
('CF','Central African Republic'),
('TD','Chad'),
('CL','Chile'),
('CN','China'),
('CX','Christmas Island'),
('CC','Cocos (Keeling) Islands'),
('CO','Colombia'),
('KM','Comoros'),
('CG','Congo'),
('CD','Congo, The Democratic Republic of the'),
('CK','Cook Islands'),
('CR','Costa Rica'),
('HR','Croatia'),
('CU','Cuba'),
('CW','Curaçao'),
('CY','Cyprus'),
('CZ','Czechia'),
('CI','Côte d''Ivoire'),
('DK','Denmark'),
('DJ','Djibouti'),
('DM','Dominica'),
('DO','Dominican Republic'),
('EC','Ecuador'),
('EG','Egypt'),
('SV','El Salvador'),
('GQ','Equatorial Guinea'),
('ER','Eritrea'),
('EE','Estonia'),
('SZ','Eswatini'),
('ET','Ethiopia'),
('FK','Falkland Islands (Malvinas)'),
('FO','Faroe Islands'),
('FJ','Fiji'),
('FI','Finland'),
('FR','France'),
('GF','French Guiana'),
('PF','French Polynesia'),
('TF','French Southern Territories'),
('GA','Gabon'),
('GM','Gambia'),
('GE','Georgia'),
('DE','Germany'),
('GH','Ghana'),
('GI','Gibraltar'),
('GR','Greece'),
('GL','Greenland'),
('GD','Grenada'),
('GP','Guadeloupe'),
('GU','Guam'),
('GT','Guatemala'),
('GG','Guernsey'),
('GN','Guinea'),
('GW','Guinea-Bissau'),
('GY','Guyana'),
('HT','Haiti'),
('HM','Heard Island and McDonald Islands'),
('VA','Holy See (Vatican City State)'),
('HN','Honduras'),
('HK','Hong Kong'),
('HU','Hungary'),
('IS','Iceland'),
('IN','India'),
('ID','Indonesia'),
('IR','Iran, Islamic Republic of'),
('IQ','Iraq'),
('IE','Ireland'),
('IM','Isle of Man'),
('IL','Israel'),
('IT','Italy'),
('JM','Jamaica'),
('JP','Japan'),
('JE','Jersey'),
('JO','Jordan'),
('KZ','Kazakhstan'),
('KE','Kenya'),
('KI','Kiribati'),
('KP','Korea, Democratic People''s Republic of'),
('KR','Korea, Republic of'),
('KW','Kuwait'),
('KG','Kyrgyzstan'),
('LA','Lao People''s Democratic Republic'),
('LV','Latvia'),
('LB','Lebanon'),
('LS','Lesotho'),
('LR','Liberia'),
('LY','Libya'),
('LI','Liechtenstein'),
('LT','Lithuania'),
('LU','Luxembourg'),
('MO','Macao'),
('MG','Madagascar'),
('MW','Malawi'),
('MY','Malaysia'),
('MV','Maldives'),
('ML','Mali'),
('MT','Malta'),
('MH','Marshall Islands'),
('MQ','Martinique'),
('MR','Mauritania'),
('MU','Mauritius'),
('YT','Mayotte'),
('MX','Mexico'),
('FM','Micronesia, Federated States of'),
('MD','Moldova, Republic of'),
('MC','Monaco'),
('MN','Mongolia'),
('ME','Montenegro'),
('MS','Montserrat'),
('MA','Morocco'),
('MZ','Mozambique'),
('MM','Myanmar'),
('NA','Namibia'),
('NR','Nauru'),
('NP','Nepal'),
('NL','Netherlands'),
('NC','New Caledonia'),
('NZ','New Zealand'),
('NI','Nicaragua'),
('NE','Niger'),
('NG','Nigeria'),
('NU','Niue'),
('NF','Norfolk Island'),
('MK','North Macedonia'),
('MP','Northern Mariana Islands'),
('NO','Norway'),
('OM','Oman'),
('PK','Pakistan'),
('PW','Palau'),
('PS','Palestine, State of'),
('PA','Panama'),
('PG','Papua New Guinea'),
('PY','Paraguay'),
('PE','Peru'),
('PH','Philippines'),
('PN','Pitcairn'),
('PL','Poland'),
('PT','Portugal'),
('PR','Puerto Rico'),
('QA','Qatar'),
('RO','Romania'),
('RU','Russian Federation'),
('RW','Rwanda'),
('RE','Réunion'),
('BL','Saint Barthélemy'),
('SH','Saint Helena, Ascension and Tristan da Cunha'),
('KN','Saint Kitts and Nevis'),
('LC','Saint Lucia'),
('MF','Saint Martin (French part)'),
('PM','Saint Pierre and Miquelon'),
('VC','Saint Vincent and the Grenadines'),
('WS','Samoa'),
('SM','San Marino'),
('ST','Sao Tome and Principe'),
('SA','Saudi Arabia'),
('SN','Senegal'),
('RS','Serbia'),
('SC','Seychelles'),
('SL','Sierra Leone'),
('SG','Singapore'),
('SX','Sint Maarten (Dutch part)'),
('SK','Slovakia'),
('SI','Slovenia'),
('SB','Solomon Islands'),
('SO','Somalia'),
('ZA','South Africa'),
('GS','South Georgia and the South Sandwich Islands'),
('SS','South Sudan'),
('ES','Spain'),
('LK','Sri Lanka'),
('SD','Sudan'),
('SR','Suriname'),
('SJ','Svalbard and Jan Mayen'),
('SE','Sweden'),
('CH','Switzerland'),
('SY','Syrian Arab Republic'),
('TW','Taiwan, Province of China'),
('TJ','Tajikistan'),
('TZ','Tanzania, United Republic of'),
('TH','Thailand'),
('TL','Timor-Leste'),
('TG','Togo'),
('TK','Tokelau'),
('TO','Tonga'),
('TT','Trinidad and Tobago'),
('TN','Tunisia'),
('TM','Turkmenistan'),
('TC','Turks and Caicos Islands'),
('TV','Tuvalu'),
('TR','Türkiye'),
('UG','Uganda'),
('UA','Ukraine'),
('AE','United Arab Emirates'),
('GB','United Kingdom'),
('US','United States'),
('UM','United States Minor Outlying Islands'),
('UY','Uruguay'),
('UZ','Uzbekistan'),
('VU','Vanuatu'),
('VE','Venezuela, Bolivarian Republic of'),
('VN','Viet Nam'),
('VG','Virgin Islands, British'),
('VI','Virgin Islands, U.S.'),
('WF','Wallis and Futuna'),
('EH','Western Sahara'),
('YE','Yemen'),
('ZM','Zambia'),
('ZW','Zimbabwe'),
('AX','Åland Islands');

create table public.globe_memberships (
  user_id uuid primary key references auth.users(id) on delete cascade,
  enabled boolean not null default false,
  region_key text references public.globe_regions(region_key),
  consent_version text,
  consented_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint globe_valid_consent check (not enabled or (region_key is not null and consent_version is not null and consent_version = '2026-09-30' and consented_at is not null))
);
alter table public.globe_memberships enable row level security;
revoke all on public.globe_memberships from public, anon, authenticated, service_role;
grant select, insert, update, delete on public.globe_memberships to authenticated;
grant select on public.globe_memberships to service_role;
create policy globe_memberships_select_own on public.globe_memberships for select to authenticated using ((select auth.uid()) = user_id);
create policy globe_memberships_insert_own on public.globe_memberships for insert to authenticated with check ((select auth.uid()) = user_id);
create policy globe_memberships_update_own on public.globe_memberships for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy globe_memberships_delete_own on public.globe_memberships for delete to authenticated using ((select auth.uid()) = user_id);

create function public.globe_stamp_consent() returns trigger
language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at := now();
  if not new.enabled then
    new.region_key := null; new.consent_version := null; new.consented_at := null;
  elsif TG_OP = 'INSERT' then
    new.consented_at := now();
  elsif not old.enabled or new.region_key is distinct from old.region_key or new.consent_version is distinct from old.consent_version then
    new.consented_at := now();
  else
    new.consented_at := old.consented_at;
  end if;
  return new;
end;
$$;
revoke all on function public.globe_stamp_consent() from public, anon, authenticated, service_role;
create trigger globe_stamp_consent before insert or update on public.globe_memberships for each row execute function public.globe_stamp_consent();

create index globe_memberships_enabled_region on public.globe_memberships(region_key) where enabled and consent_version = '2026-09-30' and consented_at is not null;
create function public.globe_region_counts() returns table(region_key text, member_count bigint)
language sql stable security invoker set search_path = '' set statement_timeout = '3s' as $$
  select m.region_key, count(*) from public.globe_memberships m
  join public.globe_regions r on r.region_key = m.region_key
  where m.enabled and m.consent_version = '2026-09-30' and m.consented_at is not null
  group by m.region_key order by m.region_key;
$$;
revoke all on function public.globe_region_counts() from public, anon, authenticated, service_role;
grant execute on function public.globe_region_counts() to service_role;
commit;
